export const verificationEmailState ={
    VERIFYING_TOKEN : "VERIFYING_TOKEN",
    VERIFIED_TOKEN : "VERIFIED_TOKEN",
    NOT_TOKEN: "NOT_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    WRONG_TOKEN: "WRONG_TOKEN",
    SENT_NEW_TOKEN: "SENT_NEW_TOKEN"

}